#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=7

banner "ready-lets-go: Firebase + Neon setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Choose your AWS region"
say "Everything else gets pinned to this. Pick the region closest to you:"
say "the database wants to sit beside the Lambda, or every query pays for"
say "the distance between them."
say ""
note "Common choices: eu-west-1 (Ireland), eu-west-2 (London),"
note "us-east-1 (N. Virginia), us-west-2 (Oregon)."
ask AWS_REGION "AWS region:"
write_env AWS_REGION "$AWS_REGION"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Firebase: create the project"
say "Firebase only handles sign-in here. Your data stays in Neon."
open_url "https://console.firebase.google.com/"
step "Click 'Create a project'."
step "Name it: ready-lets-go"
step "Google Analytics: turn it OFF. Nothing here needs it."
step "Wait for provisioning, then click Continue."
step "Project settings (gear icon, top left) -> General tab."
step "Copy the 'Project ID'. It looks like ready-lets-go-1a2b3."
note "Not the display name, and not the project number: the Project ID."
ask FIREBASE_PROJECT_ID "Paste the Project ID:"
write_env FIREBASE_PROJECT_ID "$FIREBASE_PROJECT_ID"
note "The Lambda checks every token's audience against this exact string."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Firebase: turn on sign-in methods"
say "Nothing to copy here. This stage just switches on how people log in."
open_url "https://console.firebase.google.com/project/${FIREBASE_PROJECT_ID}/authentication/providers"
step "If you see a 'Get started' button, click it."
step "Enable 'Email/Password'. Leave passwordless sign-in off for now."
step "Enable 'Google'. Pick a support email when it asks. Save."
say ""
warn "Leave 'Anonymous' switched OFF."
note "Anonymous sign-in mints a valid account nobody can ever log back into,"
note "so a trip saved against one is unreachable the moment the browser"
note "clears. Worth having one day, but only on purpose."
pause "Both providers enabled?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Firebase: register the web app"
say "This produces the config the browser needs to talk to Firebase."
open_url "https://console.firebase.google.com/project/${FIREBASE_PROJECT_ID}/settings/general"
step "Scroll to 'Your apps'. Click the web icon: </>"
step "Nickname: web. Leave Firebase Hosting UNTICKED (we deploy to AWS)."
step "Click 'Register app'."
step "You'll see a firebaseConfig block. Copy the three values below out of it."
say ""
note "These three are public. They ship inside the browser bundle, so anyone"
note "can read them. That is fine and by design: they identify your project,"
note "they don't authorise anything. Your sign-in rules do that."
ask VITE_FIREBASE_API_KEY "apiKey:"
ask VITE_FIREBASE_AUTH_DOMAIN "authDomain:"
ask VITE_FIREBASE_APP_ID "appId:"
write_env VITE_FIREBASE_API_KEY "$VITE_FIREBASE_API_KEY"
write_env VITE_FIREBASE_AUTH_DOMAIN "$VITE_FIREBASE_AUTH_DOMAIN"
write_env VITE_FIREBASE_APP_ID "$VITE_FIREBASE_APP_ID"
note "The VITE_ prefix is what lets Vite expose them to browser code."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Neon: create the database"
say "Neon is Postgres that sleeps when idle and wakes on the next query."
open_url "https://console.neon.tech/signup"
step "Sign up or log in (GitHub works)."
step "Create a project named: ready-lets-go"
step "Postgres version: take the default."
step "Region: pick the one matching ${AWS_REGION} as closely as Neon offers."
note "Neon names regions after AWS ones, so look for ${AWS_REGION} in the list."
step "Click Create. The connection details appear straight after."
pause "Project created?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Neon: the pooled connection string"
say "This is the one the app uses on every request."
open_url "https://console.neon.tech/app/projects"
step "Open your project, then the 'Connection Details' panel."
step "Make sure 'Connection pooling' is TICKED."
step "Copy the whole connection string."
note "With pooling on, the host contains '-pooler'. If it doesn't, the"
note "checkbox isn't ticked. The pooler stops a burst of Lambdas exhausting"
note "the database's connection limit."
ask_secret DATABASE_URL "Paste the pooled connection string:"
write_env DATABASE_URL "$DATABASE_URL"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Neon: the direct connection string"
say "Migrations need this one. The pooler can't run them."
step "Same panel: UNTICK 'Connection pooling'."
step "Copy the string again. This time the host has no '-pooler'."
note "Schema changes use session-level features that the pooler drops, so"
note "migrations talk to the database directly while the app never does."
ask_secret DATABASE_URL_UNPOOLED "Paste the direct connection string:"
write_env DATABASE_URL_UNPOOLED "$DATABASE_URL_UNPOOLED"

SKIPPED+=("Load these into SST once sst.config.ts exists: sst secret set DatabaseUrl / DatabaseUrlUnpooled / FirebaseProjectId")

finish
